---
- name: Préparer les noeuds du cluster MGGT1103
  hosts: k3s_cluster
  become: true
  gather_facts: true

  vars_files:
    - secrets.yml

  pre_tasks:
    - name: Vérifier le système d'exploitation
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Ubuntu"
          - ansible_distribution_major_version | int == 24
        fail_msg: >-
          Système incompatible :
          {{ ansible_distribution }} {{ ansible_distribution_version }}
        success_msg: >-
          Système compatible :
          {{ ansible_distribution }} {{ ansible_distribution_version }}
      tags:
        - always

  roles:
    - role: common
      tags:
        - common

    - role: docker
      tags:
        - docker

    - role: k3s_server
      when: inventory_hostname in groups['master']
      tags:
        - k3s_server
